[fix]

diff --git a/0x0C-web_server/1-install_ngix_web_server b/0x0C-web_server/1-install_ngix_web_server
--- a/0x0C-web_server/1-install_ngix_web_server
+++ b/0x0C-web_server/1-install_ngix_web_server
@@ -1,1 +1,19 @@
-domain.tech
+#!/usr/bin/env bash
+# setup and run nginx server
+
+apt-get update -y
+if ! apt-get install -y nginx;
+then
+	echo "Failed to install nginx" 1>&2
+	exit 1
+fi
+
+echo "Holberton School" > /var/www/html/index.html
+
+if ! service nginx start;
+then
+	echo "Failed to start nginx" 1>&2
+	exit 1
+fi
+
+exit 0
diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,9 +1,33 @@
-
 #!/usr/bin/env bash
-# Script to install ngix and add redirect page
-sudo apt-get update
-sudo apt-get -y install nginx
-echo "Holberton School" | sudo tee /var/www/html/index.html
-sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
-sudo nginx -t
-sudo service nginx restart
+# setup nginx server
+
+apt-get update -y
+
+if ! apt-get install -y nginx;
+then
+	echo "Failed to install nginx" 1>&2
+	exit 1
+be
+echo -e \
+"server {
+ 	listen 80 default_server;
+	listen [::]:80 default_server;
+	root /var/www/html;
+	index index.html;
+	server_name _;
+	location / {
+		try_files \$uri \$uri/ =404;
+	}
+	location /redirect_me {
+		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
+	}
+}" > /etc/nginx/sites-available/default
+echo "Holberton School" > /var/www/html/index.html
+
+if ! service nginx restart;
+then
+	echo "Failed to start nginx" 1>&2
+	exit 1
+be
+
+exit 0
